# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Atif Quamar'
    description: 'Research Assistant'
    twitter: 'atifquamar07'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Atif Quamar. All rights reserved.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  seo:
    enable: true
    keywords: 'machine learning, artificial intelligence, computer vision, data science, research, deep learning, neural networks, ai, ml, dl, phd, research intern'
    author: 'Atif Quamar'
    robots: 'index, follow'
    canonical_url: true
  social:
    enable: true
    open_graph:
      enable: true
      type: 'website'
      locale: 'en_US'
      site_name: 'Atif Quamar'
      images:
        - 'media/icon.png'
    twitter_card:
      enable: true
      card: 'summary_large_image'
      site: '@atifquamar07'
      creator: '@atifquamar07'
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/atifquamar07/atifquamar07.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
